-- ============================================================
-- Import 45 partenaires — données initiales annuaire
-- ON CONFLICT (slug) DO NOTHING → idempotent, rejouable
-- ============================================================

INSERT INTO public.pro_partners (name, slug, type, directory_category, subcategories, address, postal_code, city, description, website_url, facebook_url, instagram_url, logo_url, partner_status, is_public, status, source_import)
VALUES
-- ── Boutiques & librairies ──
('Librairie le Dojo', 'librairie-le-dojo', 'boutique', 'boutiques_librairies', ARRAY['librairie'], '3 Rue Alfred Mortier', '06000', 'Nice', 'Vente de mangas, de BD, d''accessoires, figurines, exclusivités, produits collectors et goodies japonais', 'https://www.alfa-bd.fr', 'https://www.facebook.com/librairieledojo', 'https://www.instagram.com/ledojo_alfabd/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942891/Dojo_logo_png_ph5xgp.png', 'opportunite', true, 'active', 'import_csv_2026'),

('GameCash', 'gamecash', 'boutique', 'boutiques_librairies', ARRAY['boutique_specialisee'], '20 rue Jules Bianchi', '06200', 'Nice', 'Achat/vente jeux vidéo, consoles, produits dérivés, retrogaming, goodies, pop culture', 'https://www.gamecash.fr/magasin-gamecash-nice-m182.html', 'https://www.facebook.com/GamecashNice', 'https://www.instagram.com/gamecashnice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941893/gamecash_nice_png_ebdgxb.png', 'opportunite', true, 'active', 'import_csv_2026'),

('AltF4', 'altf4', 'lieu_culturel', 'boutiques_librairies', ARRAY['bar_esport'], '20 Rue Jules Bianchi, Nice', '06200', 'Nice', 'Espace bar-gaming et restauration dédié au jeu vidéo sur PC et consoles', 'https://altf4esportnice.my.canva.site', '', 'https://www.instagram.com/altf4esport.nice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942960/AltF4_png_carre_wfzq8w.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Otak', 'otak', 'boutique', 'boutiques_librairies', ARRAY['librairie'], '51 Bd Carnot', '06400', 'Cannes', 'Librairie spécialisée (manga, produits dérivés japonais, figurines, jeux)', 'https://www.otak.fr', 'https://www.facebook.com/people/Otak/61552497625212/', 'https://www.instagram.com/otak.fr/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941120/logo_OTAK_png_r703hm.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Librairie du Cap', 'librairie-du-cap', 'boutique', 'boutiques_librairies', ARRAY['librairie'], '217 Av. Eugène Donadeï', '06700', 'Saint-Laurent-du-Var', 'Vente de mangas, BD, comics, jeux de sociétés, figurines, littérature jeunesse et produits dérivés', 'https://www.librairieducap.com', 'https://www.facebook.com/profile.php?id=100093576970578', 'https://www.instagram.com/librairieducap/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752945812/347425391_115746764887889_2704080071050670586_n_ed1ddt.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Galerie TCG', 'galerie-tcg', 'boutique', 'boutiques_librairies', ARRAY['boutique_specialisee'], '22 Rue Valazé', '06700', 'Saint-Laurent-du-Var', 'Boutique spécialisée cartes à collectionner (TCG) et goodies', 'https://voggt.com/profiles/857653', '', 'https://www.instagram.com/galerie_tcg/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752952159/Galerie_TCG_carre_png_p4cvbf.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Librairie Dernier Rempart', 'librairie-dernier-rempart', 'boutique', 'boutiques_librairies', ARRAY['librairie'], '10 avenue Robert Soleau', '06600', 'Antibes', 'Vente de mangas, BD, romans, jeux de société', 'https://www.dernier-rempart.com', 'https://www.facebook.com/DernierRempartJeuxMangas', 'https://www.instagram.com/dernier_rempart_jeux_et_mangas/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942322/277817211_398045322325403_7558863940638545694_n_s5cetg.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Cosplay Smart', 'cosplay-smart', 'boutique', 'boutiques_librairies', ARRAY['boutique_en_ligne'], NULL, NULL, NULL, 'Vente de matériaux, accessoires et produits pour la création de costumes de cosplay', 'https://cosplaysmart.com', 'https://www.facebook.com/cosplaysmart', 'https://www.instagram.com/cosplaysmartfr/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942241/331531523_1364229837452812_510241111470137358_n_mlznld.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Cash Express Nice', 'cash-express-nice', 'boutique', 'boutiques_librairies', ARRAY['boutique_specialisee'], '29 avenue Malaussena', '06000', 'Nice', 'Achat et revente d''accessoires, jeux vidéo, high-tech, téléphonie, bijoux, multimédia et autres produits d''occasion', 'https://www.cashexpress.fr', 'https://www.facebook.com/cashexpressnice', 'https://www.instagram.com/cashexpressnice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942134/292359442_501260321799855_3884853220252512207_n_b9ghlr.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Partenaires associatifs ──
('Face06', 'face06', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], '9 rue d''Alsace Lorraine', '06000', 'Nice', 'Fédération des associations étudiantes, actions de solidarité étudiante, événements et accompagnement social', 'https://face06.org', 'https://www.facebook.com/face06nice', 'https://www.instagram.com/face_06/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942864/Face06_png_xg4wom.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Eventasia', 'eventasia', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], NULL, NULL, NULL, 'Cours Manga, Danse K-Pop et organisateur d''événements', 'https://www.eventasia-asso.fr', 'https://www.facebook.com/eventasiaassociation/', 'https://www.instagram.com/eventasia.asso/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942899/logo_eventasia_carre_png_dupvjs.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Rigel E-Sport', 'rigel-e-sport', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], NULL, NULL, NULL, 'Structure eSport basée sur Rocket League et Valorant sur Nice', 'https://www.rigelesport.fr/home', '', 'https://www.instagram.com/rigel.esport/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942854/rigel_e_sport_logo_png_ouehhr.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Pokevents', 'pokevents', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], NULL, NULL, NULL, 'Organisation d''événements et de tournois Pokémon (communauté vidéoludique)', 'https://www.helloasso.com/associations/pokevents', '', 'https://www.instagram.com/pokevents.officiel/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752944372/Pokevents_logo_png_carre_osmngq.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Ecole Tsubaki', 'ecole-tsubaki', 'institution', 'partenaires_associatifs', ARRAY['enseignement'], '11 Rue Pertinax', '06000', 'Nice', 'Cours de japonais tous niveaux et ateliers culturels (art floral, calligraphie, kimono, origami)', 'https://ecoletsubaki.fr', 'https://www.facebook.com/ecoletsubaki/', 'https://www.instagram.com/ecoletsubaki/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752952646/Ecole_Tsubaki_tjtjwu.png', 'opportunite', true, 'active', 'import_csv_2026'),

('The Cosplayeurs League', 'the-cosplayeurs-league', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], NULL, NULL, NULL, 'Association française de cosplay', 'https://www.cosplayleague.fr', 'https://www.facebook.com/cosplayersleague', 'https://www.instagram.com/thecosplayersleague/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953214/The_cosplayeurs_league_carre_veslhd.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Fur''Sud Est', 'fur-sud-est', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], NULL, NULL, NULL, 'Organisation de meetups et animations communautaires autour du fandom furry', 'https://fursudest.fr', '', 'https://www.instagram.com/fur.sud.est/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1755722599/Logo_PNG_Fursudest_MAJ_2025_afblyk.png', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Acteurs publics ──
('Université Côte d''Azur', 'universite-cote-dazur', 'institution', 'acteurs_publics', ARRAY['enseignement'], '28 avenue Valrose', '06000', 'Nice', 'Enseignement supérieur, recherche', 'https://univcotedazur.fr', 'https://www.facebook.com/UnivCotedAzur', 'https://www.instagram.com/univ_cotedazur/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940920/UCA_Logo_transparent_enj7po.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Crous Nice Toulon', 'crous-nice-toulon', 'institution', 'acteurs_publics', ARRAY['service_public_institution'], '26 route de Turin', '06300', 'Nice', 'Établissement public administratif (services étudiants)', 'https://www.crous-nice.fr', 'https://www.facebook.com/crousnicetoulon', 'https://www.instagram.com/crousnicetoulon/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940934/Crous-logo-nice-toulon-rouge_40678_kywtzk.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Maison de l''Etudiant', 'maison-de-letudiant', 'institution', 'acteurs_publics', ARRAY['service_public_institution'], '5 avenue François Mitterrand', '06300', 'Nice', 'Lieu de référence d''informations, d''événements et de rencontres pour les étudiants', 'https://etudiants.nice.fr', 'https://www.facebook.com/lamdenice', 'https://www.instagram.com/mde.nice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940892/298935342_102370315930771_999123045570238723_n_usrrrd.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Ville de Nice', 'ville-de-nice', 'collectivite', 'acteurs_publics', ARRAY['service_public_institution'], '5 Rue de l''Hôtel de ville', '06000', 'Nice', 'Collectivité territoriale / Mairie', 'https://www.nice.fr', 'https://www.facebook.com/VilledeNice', 'https://www.instagram.com/villedenice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941335/LOGO_VILLE_DE_NICE_H_QUADRI_TNOIR_k3cloj.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Bibliothèque de Nice', 'bibliotheque-de-nice', 'institution', 'acteurs_publics', ARRAY['bibliotheque_municipale'], NULL, NULL, NULL, 'Bibliothèque, médiathèque, prêt de documents, activités culturelles', 'https://bmvr.nice.fr', 'https://www.facebook.com/bmvrNice/', 'https://www.instagram.com/bibnice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752942053/Biblioth%C3%A8que_Nice_png_jh4obx.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Agis 06 - Cap Jeunesse', 'agis-06-cap-jeunesse', 'institution', 'acteurs_publics', ARRAY['service_public_institution'], '6 avenue Félix Faure', '06000', 'Nice', 'Information, accompagnement et animation pour les jeunes, soutien à la jeunesse locale', 'https://cap-jeunesse.fr/', 'https://www.facebook.com/capjeunesseca', 'https://www.instagram.com/capjeunesseca/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941201/323768214_3766675103618083_1648418041499790129_n_wdydtc.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Ville de Saint Laurent du Var', 'ville-de-saint-laurent-du-var', 'collectivite', 'acteurs_publics', ARRAY['service_public_institution'], '222 Esp. du Levant', '06700', 'Saint-Laurent-du-Var', 'Collectivité territoriale / Mairie', 'https://saintlaurentduvar.fr', 'https://www.facebook.com/VilledeSaintLaurentduVar/', 'https://www.instagram.com/saintlaurentduvarofficiel/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941873/Mairie_Saint_Laurent_du_Var_lp3wst.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Ville de Peymeinade', 'ville-de-peymeinade', 'collectivite', 'acteurs_publics', ARRAY['service_public_institution'], '11 Bd du Général de Gaulle', '06530', 'Peymeinade', 'Collectivité territoriale / Mairie', 'https://www.peymeinade.fr', 'https://www.facebook.com/VillePeymeinadeOfficiel/', 'https://www.instagram.com/villedepeymeinade/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941880/Mairie_de_Peymeinade_uuasnm.png', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Cinémas ──
('Cinéma Variétés', 'cinema-varietes', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '5 boulevard Victor Hugo, 06000 Nice', NULL, 'Nice', 'Exploitation de salles de cinéma, distribution de films', 'https://www.cinemavarietes.fr', 'https://www.facebook.com/cinemavarietesnice', 'https://www.instagram.com/cinemavarietesnice/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752943116/Cin%C3%A9ma_Vari%C3%A9t%C3%A9s_png_hc8job.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Cineum Cannes', 'cineum-cannes', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '230 avenue Francis Tonner', '06150', 'Cannes', 'Exploitation de salles de cinéma, distribution de films', 'https://www.cineum.fr', 'https://www.facebook.com/cineumcannes/', 'https://www.instagram.com/cineumcannes/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940985/298561427_551651333413435_5087063078027658426_n_eslddl.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

('Pathé Lingostière', 'pathe-lingostiere', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '606 Bd du Mercantour', '06200', 'Nice', 'Exploitation de salles de cinéma, distribution de films', 'https://www.pathe.fr/cinemas/cinema-pathe-lingostiere', '', 'https://www.instagram.com/pathelingostiere/', NULL, 'opportunite', true, 'active', 'import_csv_2026'),

('Pathé Gare du Sud', 'pathe-gare-du-sud', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '6 All. Philippe Seguin', '06000', 'Nice', 'Exploitation de salles de cinéma, distribution de films', 'https://www.pathe.fr/cinemas/cinema-pathe-gare-du-sud', 'https://www.facebook.com/PatheGareDuSud', 'https://www.instagram.com/pathe.garedusud/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752943095/path%C3%A9_carre_kqr9ap.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Pathé Massena', 'pathe-massena', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '31 Avenue Jean Médecin', '06000', 'Nice', 'Exploitation de salles de cinéma, distribution de films', 'https://www.pathe.fr/cinemas/cinema-pathe-massena', 'https://www.facebook.com/PatheMassenaParis', 'https://www.instagram.com/pathemassena/', NULL, 'opportunite', true, 'active', 'import_csv_2026'),

('Cinéma Olympia', 'cinema-olympia', 'lieu_culturel', 'cinemas', ARRAY['cinema'], '5 Rue de la Pompe', '06400', 'Cannes', 'Exploitation de salles de cinéma, distribution de films', 'https://www.cinemaolympia-cannes.fr', 'https://www.facebook.com/cinemaolympiacannes/', 'https://www.instagram.com/cinema_olympia_cannes/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1755616386/Cin%C3%A9ma_olympia_PNG__qyekpk.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Eurozoom', 'eurozoom', 'societe', 'cinemas', ARRAY['distributeur'], NULL, NULL, NULL, 'Distribution de films d''animation (japonais, européen)', 'https://www.eurozoom.fr', 'https://www.facebook.com/eurozoom.distributeur', 'https://www.instagram.com/eurozoomcinema/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940880/Logo-Eurozoom_hbboht.png', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Artistes & Créateurs ──
('MeanCatTV', 'meancattv', 'auto_entrepreneur', 'artistes_createurs', ARRAY['streamer_createur_contenu'], NULL, NULL, NULL, 'Artistes reprenant génériques d''anime interprétés en live, musiques originales, discussions pop culture', 'https://eliminate.fr/categorie-produit/meancattv/', 'https://www.twitch.tv/meancattv', 'https://www.instagram.com/meancattv/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953498/MeanCatTV_logo_carre_w3fund.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Joel Lange', 'joel-lange', 'auto_entrepreneur', 'artistes_createurs', ARRAY['auteur_mangaka'], NULL, NULL, NULL, 'Auteur Mangaka Les Aventuriers de Novagorone', 'https://www.neiko-editions.com', 'https://www.facebook.com/joellangeartiste1', 'https://www.instagram.com/joellange_artiste/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953374/joel_lange_logo_carre_gtjsi2.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Fantaisie de Naty', 'fantaisie-de-naty', 'auto_entrepreneur', 'artistes_createurs', ARRAY['artiste_illustrateur'], NULL, NULL, NULL, 'Créations fait main inspirées du fantastique, des fées, du steampunk et de l''univers elfique : bijoux, diadèmes', 'https://www.etsy.com/fr/shop/FantaisieDeNaty', 'https://www.facebook.com/fantaisiedenaty', 'https://www.instagram.com/fantaisiedenaty', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953226/Fantaisie_de_Naty_carre_bjepmw.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Frimousserie', 'frimousserie', 'auto_entrepreneur', 'artistes_createurs', ARRAY['artiste_illustrateur'], NULL, NULL, NULL, 'Créations artisanales en bois sculpté, ficelle et matières naturelles à thèmes fantasy, médiéval, geek et nature', 'https://www.etsy.com/fr/shop/Boisetficelle', 'https://www.facebook.com/boisetficelle', 'https://www.instagram.com/la.frimousserie/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953234/Frimousserie_carre_gwv80t.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Délires de Gnapou', 'delires-de-gnapou', 'auto_entrepreneur', 'artistes_createurs', ARRAY['artiste_illustrateur'], NULL, NULL, NULL, 'Fabrication artisanale d''illustrations, badges, pins et produits originaux', 'https://lesdeliresdugnapou.com', '', 'https://www.instagram.com/les.delires.du.gnapou/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953208/D%C3%A9lires_du_gnapou_carre_qeyr7k.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Pimp My Retrogame', 'pimp-my-retrogame', 'boutique', 'artistes_createurs', ARRAY['boutique_specialisee'], NULL, NULL, NULL, 'Personnalisation de consoles rétro, modding, stickers et accessoires geek faits main.', 'https://www.vinted.fr/member/207524410-pimpmyretrogame', '', 'https://www.instagram.com/pimpmyretrogame/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953305/Logo_pimpmyretrogame_uki2al.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Art''Cade Design', 'art-cade-design', 'auto_entrepreneur', 'artistes_createurs', ARRAY['artiste_illustrateur'], NULL, NULL, NULL, 'Conception et personnalisation de bornes d''arcade rétro/multijeux', 'https://www.artcadedesign.fr', 'https://www.facebook.com/artcadedesign/', 'https://www.instagram.com/art_cade_design/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752953633/Arcade_Design_carre_logo_qhtms3.png', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Événements & lieux culturels ──
('Play Azur Festival', 'play-azur-festival', 'societe', 'evenements_lieux_culturels', ARRAY['evenement_festival'], NULL, NULL, NULL, 'Festival annuel autour de la culture pop, internet, science, invités YouTube, cosplay, jeux vidéo, animation japonaise', 'https://playazur.fr', 'https://www.facebook.com/search/top?q=play%20azur%20festival', 'https://www.instagram.com/playazur/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752940905/Play_Azur_png_uofn9l.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Cap3000', 'cap3000', 'societe', 'evenements_lieux_culturels', ARRAY['centre_commercial'], '217 Av. Eugène Donadeï', '06700', 'Saint-Laurent-du-Var', 'Grand centre commercial en bord de mer, boutiques mode, loisirs, beauté & nombreux restaurants', 'https://www.cap3000.com', 'https://www.facebook.com/CentreCommercialCap3000', 'https://www.instagram.com/cap3000_cotedazur/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752945622/Cap3000_png_ldu5xz.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Sharks d''Antibes', 'sharks-dantibes', 'association', 'evenements_lieux_culturels', ARRAY['club_sportif'], '250 rue Émile Hugues', '06600', 'Antibes', 'Club professionnel de basketball', 'https://www.sharks-antibes.com', 'https://www.facebook.com/AntibesSharks', 'https://www.instagram.com/antibessharks/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752944435/Sharks_carre_png_qnkwf2.png', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── Restauration ──
('Restaurant Otaku', 'restaurant-otaku', 'societe', 'restauration', ARRAY['restaurant'], '2 rue Paganini', '06000', 'Nice', 'Cuisine japonaise (bento, ramen, donburi, gyoza)', '', 'https://www.facebook.com/OTAKUnice/', 'https://www.instagram.com/otakurestaurantjaponais/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941134/restaurant_OTAKU_png_zaruar.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Gare du Sud - Mediterraneo', 'gare-du-sud-mediterraneo', 'societe', 'restauration', ARRAY['restaurant'], '35 avenue Malaussena', '06000', 'Nice', 'Restauration sur le pouce de spécialités méditerranéennes, pizzas, pâtes, salades, desserts italiens', 'https://mediterraneo-nice.com', 'https://www.facebook.com/mediterraneonice', 'https://www.instagram.com/mediterraneo_garedusud', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752943006/Mediterraneo_Gare_du_Sud_Png_tcxa8v.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Restaurant Panasia', 'restaurant-panasia', 'societe', 'restauration', ARRAY['restaurant'], '217 Av. Eugène Donadeï', NULL, 'Saint-Laurent-du-Var', 'Cuisine asiatique haut de gamme : spécialités chinoises, thaïlandaises, vietnamiennes, japonaises', 'https://www.panasia.fr', 'https://www.facebook.com/restaurantpanasia/', 'https://www.instagram.com/panasia.restaurant/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941841/Panasia_png_y6pi66.png', 'opportunite', true, 'active', 'import_csv_2026'),

('Rice Street Cap3000', 'rice-street-cap3000', 'societe', 'restauration', ARRAY['restaurant'], '217 Av. Eugène Donadeï', '06700', 'Saint-Laurent-du-Var', 'Restauration rapide aux saveurs asiatiques : rice bowls, yakitoris, street food d''inspiration japonaise', 'https://www.ricestreet.fr', 'https://www.facebook.com/ricestreet.fr', 'https://www.instagram.com/rice_street_cap3000/', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1752941150/294740581_418313447010114_1186730966000261129_n_agw4cj.jpg', 'opportunite', true, 'active', 'import_csv_2026'),

-- ── BDE (partenaires associatifs) ──
('BDE Campus Valrose', 'bde-campus-valrose', 'association', 'partenaires_associatifs', ARRAY['association_declaree'], '28 Av. Valrose', '06100', 'Nice', 'Organise des événements festifs, culturels et sportifs pour animer la vie étudiante sur le campus', 'https://bde-valrose1.odoo.com/', 'https://www.facebook.com/bde.sciences.de.valrose', 'https://www.instagram.com/bde_sciences_valrose', 'https://res.cloudinary.com/dkw8snibz/image/upload/v1762346900/images_3_tf5ehh.png', 'opportunite', true, 'active', 'import_csv_2026')

ON CONFLICT (slug) DO NOTHING;
